=head1 Sequence Functions

Sequences are at the moment, lists and strings.
If any other form of sequence should be included, these functions will also work with them.

=head2 Functions

=over 4

=cut


=item concat

 S T  ->  U

Sequence U is the concatenation of sequences S and T.

=cut

.sub 'concat'
	.local pmc stack
	stack = get_global 'funstack'
	$P0 = stack.'pop'('String', 'ResizablePMCArray')
	$S0 = typeof $P0
	$P1 = stack.'pop'('String', 'ResizablePMCArray')
	$S1 = typeof $P0
	
	if $S0 == $S1 goto allgood

	print "Cannot append different types"
	
allgood:
	if $S0 == 'String' goto concat_string
	
concat_array:
	$P1.'append'($P0)
	stack.'push'($P1)
	goto finish

concat_string:
	concat $P1, $P0
	stack.'push'($P1)
	
finish:
.end

=item reverse

 S  ->  R

Sequence R is the reverse of sequence S.

=cut

.sub 'reverse'
	.local pmc stack, value
	stack = get_global 'funstack'
	value = stack.'pop'('String', 'ResizablePMCArray')
	$S0 = typeof value
	if $S0 == 'ResizablePMCArray' goto reverse_array
	
reverse_string:
	$S0 = value
	reverse $S0
	value = $S0
	stack.'push'(value)
	goto finish
	
reverse_array:
	.local pmc revarray
	revarray = new 'ResizablePMCArray'
	
iter_loop:
	unless value goto iter_end
	$P0 = shift value
	unshift revarray, $P0
	goto iter_loop
iter_end:
	stack.'push'(revarray)

finish:
	.return()
.end


=back
=cut
